# Generated by Django 4.0.4 on 2022-04-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images/', verbose_name='Фото'),
        ),
    ]
